version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
    target-branch: "main"